In [1]:
import pandas as pd


In [2]:
data  = pd.read_csv('Email spam.csv')

In [3]:
data.head(10)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1
5  Subject: great nnews  hello , welcome to medzo...     1
6  Subject: here ' s a hot play in motion  homela...     1
7  Subject: save your money buy getting this thin...     1
8  Subject: undeliverable : home based business f...     1
9  Subject: save your money buy getting this thin...     1

In [4]:
# lets see the spam examples
print(data['text'][1])

Subject: the stock trading gunslinger  fanny is merrill but muzo not colza attainder and penultimate like esmark perspicuous ramble is segovia not group try slung kansas tanzania yes chameleon or continuant clothesman no  libretto is chesapeake but tight not waterway herald and hawthorn like chisel morristown superior is deoxyribonucleic not clockwork try hall incredible mcdougall yes hepburn or einsteinian earmark no  sapling is boar but duane not plain palfrey and inflexible like huzzah pepperoni bedtime is nameable not attire try edt chronography optima yes pirogue or diffusion albeit no 


In [5]:
df = data[data['spam']==0]

In [6]:
# Non-Spam Example
print(df['text'][1369])

Subject: sacramento weather station  fyi  - - - - - - - - - - - - - - - - - - - - - - forwarded by mike a roberts / hou / ect on 09 / 20 / 2000  09 : 06 am - - - - - - - - - - - - - - - - - - - - - - - - - - -  scott tholan @ enron  09 / 19 / 2000 07 : 57 pm  to : mark tawney / hou / ect @ ect , gary taylor / hou / ect @ ect , mike a  roberts / hou / ect @ ect  cc : chris clark / na / enron @ enron  subject : sacramento weather station  hey guys ,  we ' re talking to a contractor ( s ) that can build us a weather station  ( hopefully very quickly ) for placement in sacramento , california . for a  variety of legal , contractor , and operational reasons , i need to confirm some  of the following requirements as soon as possible so we can proceed :  a ) you need rainfall , snowfall , and temperature measurement from one ,  high - accuracy commercially available weather station .  b ) you need a daily feed of this data to enron ' s weather desk : does this  mean one data dump at a set tim

In [7]:
# information reguarding the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    5728 non-null   object
 1   spam    5728 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 89.6+ KB


In [8]:
# Columns and rows present in the dataset
print("This dataset contains:",data.shape[0],"Rows and ",data.shape[1],"Columns")

This dataset contains: 5728 Rows and  2 Columns


In [9]:
data['spam'].unique()

array([1, 0], dtype=int64)

In [10]:
# Provide the set of features we have 
data.columns

Index(['text', 'spam'], dtype='object')

In [11]:
data['spam'].value_counts().head(32).plot(kind='bar', figsize=(7,10))

<AxesSubplot:>

# Transformation

In [12]:
# missing values
data.isnull().sum()

text    0
spam    0
dtype: int64

In [13]:
# Duplicates
data.duplicated().sum()

33

In [14]:
# Drop duplicated values
data.drop_duplicates(inplace=True)

## As the data included 'subject' in begining of every email hence it needs to be removed

In [15]:
for i in range(data.shape[0]):
    data.loc[i, 'text'] = data.loc[i, 'text'].split(' ', 0)[0]

KeyError: 2155

In [16]:
data.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [17]:
# Saving the cleaned data as a csv file
data.to_csv('cleaned_data.csv',index=False)

In [ ]:
exit()

# The Machine learning Pipeline

In [18]:
# The NLP methodology (Text Processing, Tokenize, Clean, Normalize)

Normalize: In order to simply the text we generally lemmatize or stem in this step 
Generally refers to doing things in order with use of morphogically or vocabulary analysis of words.

In [20]:
# Tokenize the data

In [22]:
def tokenize(text):
    # Normalize:convert to lower case and remove the punctuation
    text = re.sub(r"[^a-zA-Z0-9]","",text.lower().strip())
    # Tokenizing: Split text into words
    tokens = word_tokenize(text)
    # Remove the stop words: if a token is a stop word then remove it
    words = [w for w in tokens if w not in stop.words("english")]
    # Lemmatize and stemming
    lemmed_words = [WordNetLemmatizer().lemmatize(w) for w in words]
    
    clean_tokens = []
    
    for i in lemmed_words:
        clean_tokens.append(i)
        
        #back to string from list
    text = "".join(clean_tokens)
    return text
    
    # return the clean string

# Machine Learning pipeline

In [59]:
pip install sklearn

  Using cached sklearn-0.0.tar.gz (1.1 kB)
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1309 sha256=0ee2fd26064e756b9fad289208dd25013fa39e24fc89c1222641cd548b3283aa
  Stored in directory: c:\users\amay\appdata\local\pip\cache\wheels\46\ef\c3\157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


In [24]:
# importing the libraries
import pandas as pd
import numpy as np

In [46]:
# importing text processing libraries
import nltk
nltk.download('stopwords')
nltk.download(['punkt','wordnet','averaged_perceptron_tagger'])
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import re

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Amay\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Amay\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Amay\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Amay\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [61]:
# Model Libraries
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

In [30]:
# Save the Model
import joblib
from joblib import dump, load

In [32]:
# Evaluate the Model
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Retrive the Data

Now lets work with the data 

In [33]:
data = pd.read_csv('cleaned_data.csv')

In [52]:
# change the name of the columns
data.rename(columns ={'spam':'Label','text':'Email'},inplace=True)

## NLP : Text Analysis and Processing

In [53]:
stop_words = stopwords.words("english")
lemmatizer = WordNetLemmatizer()

In [54]:
def tokenize(text):

   #1. Normalize: Convert to lower case and remove punctuation
    text = re.sub(r"[^a-zA-Z0-9]", " ", text.lower().strip())
    
   #2. Tokenizing: split text into words
    tokens = word_tokenize(text)
    
   #3. Remove stop words: if a token is a stop word, then remove it
    words = [w for w in tokens if w not in stopwords.words("english")]
    
    #4. Lemmatize and Stemming
    lemmed_words = [WordNetLemmatizer().lemmatize(w) for w in words]
    
    clean_tokens = []
    
    for i in lemmed_words:
        clean_tokens.append(i)
        
        ## back to string from list
    text = " ".join(clean_tokens)
    return text

    #return clean_tokens  

In [55]:
data['Pro_Text'] = data['Email'].apply(lambda x: tokenize(x))
data.head()

Email  Label  \
0  Subject: naturally irresistible your corporate...      1   
1  Subject: the stock trading gunslinger  fanny i...      1   
2  Subject: unbelievable new homes made easy  im ...      1   
3  Subject: 4 color printing special  request add...      1   
4  Subject: do not have money , get software cds ...      1   

                                            Pro_Text  
0  subject naturally irresistible corporate ident...  
1  subject stock trading gunslinger fanny merrill...  
2  subject unbelievable new home made easy im wan...  
3  subject 4 color printing special request addit...  
4  subject money get software cd software compati...

In [63]:
# Assignining the independent features(text) to x variable and the target to y variable

X = data['Email']
y = data['Label']

## Train Test Split of the data

In [64]:
# The split into traning 77% and Test 33%

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33, random_state=42)

In [66]:
pipeline = Pipeline([
    ('vect',CountVectorizer(tokenizer=tokenize)),
    ('tfidf',TfidfTransformer()),
    ('clf',MultinomialNB())
])

In [68]:
# train the pipeline
pipeline.fit(X_train,y_train)

Pipeline(steps=[('vect',
                 CountVectorizer(tokenizer=<function tokenize at 0x000001EDEB5ECEE8>)),
                ('tfidf', TfidfTransformer()), ('clf', MultinomialNB())])

## Test the pipeline

In [69]:
# Predict using the trained model
predicted = pipeline.predict(X_test)

## Evaluate the Model

In [70]:
# Evalutaion of the Model
from sklearn.metrics import accuracy_score
# accuracy, precision, recall
accuracy = accuracy_score(y_test,predicted)
print('Accuracy:', round(accuracy,2))

print("other Metrics:")
print(classification_report(y_test,predicted))

Accuracy: 0.74
other Metrics:
              precision    recall  f1-score   support

           0       0.74      1.00      0.85      1390
           1       0.00      0.00      0.00       490

    accuracy                           0.74      1880
   macro avg       0.37      0.50      0.43      1880
weighted avg       0.55      0.74      0.63      1880



C:\Users\Amay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Amay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Amay\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [72]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,predicted))

[[1390    0]
 [ 490    0]]


In [73]:
# Precision Recall score
from sklearn.model_selection import learning_curve
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import precision_recall_curve

In [74]:
## Plot confusion matrix
classes = np.unique(y_test)

cm = confusion_matrix(y_test, predicted)
fig, ax = plt.subplots()

sns.heatmap(cm, annot=True, fmt='d', ax=ax, cmap=plt.cm.Blues, 
            cbar=False)
ax.set(xlabel="predicted labels", ylabel="True labels", xticklabels=classes, 
       yticklabels=classes, title="Confusion matrix")
plt.yticks(rotation=0)

(array([0.5, 1.5]), [Text(0, 0.5, '0'), Text(0, 1.5, '1')])

In [75]:
# Saving the model
import pickle

file_name = "pipelinemodel1"
pickle.dump(pipeline, open(file_name,'wb'))